authentication/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns('',
    # The password reset form view:
    url(r'^password_reset/$',
        views.PasswordResetView.as_view(),
        name='password_reset'
    ),
    # The password reset confirmation view:
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'django.contrib.auth.views.password_reset_confirm',
        name='password_reset_confirm'
    ),

    url(r'^login/$',
        'django.contrib.auth.views.login',
        kwargs={'template_name': 'authentication/login.html'},
        name='login'
    ),

    url(r'^logout/$',
        'django.contrib.auth.views.logout',
        kwargs={'next_page': '/login'},
        name='logout'),

    url(
        r'^password/reset/done/$',
        'django.contrib.auth.views.password_reset_done',
        kwargs={'template_name': 'authentication/password_reset_done.html'},
        name='password_reset_done'
    ),
)

core/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import (login,
                                       logout)
from . import views

urlpatterns = [
    url(r'^', include('churchlife.authentication.urls', namespace='authentication')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.IndexView.as_view(), name='index'),

    url(
        r'^api/v1/user_session/$', 
        views.UserSessionView.as_view({
            'get': 'list',
            # 'post': 'create',
        }),
        name='user_session'
    ),

    url(
        r'^api/v1/user/$', 
        views.UserView.as_view({
            'get': 'list',
            # 'post': 'create',
        }),
        name='user'
    ),

    url(
        r'^api/v1/member/$', 
        views.MemberView.as_view({
            'get': 'list',
            'post': 'create',
        }),
        name='member'
    ),

    url(
        r'^api/v1/member/(?P<pk>\d+)/$', 
        views.MemberView.as_view({
            'get': 'retrieve',
            'put': 'update',
            'patch': 'update',
        }),
        name='member-detail'
    ), 

    url(
        r'^api/v1/member/search/$', 
        views.MemberSearchView.as_view({
            'get': 'list'
        }),
        name='member-search'
    ),

    url(
        r'^api/v1/organization/$', 
        views.OrganizationView.as_view({
            'get': 'list',
            'post': 'create',
        }),
        name='organization'
    ),

    url(
        r'^api/v1/organization/(?P<pk>\d+)/$', 
        views.OrganizationView.as_view({
            'get': 'retrieve',
            'put': 'update',
            'patch': 'update',
        }),
        name='organization-detail'
    ),    

    url(
        r'^api/v1/event/$', 
        views.EventView.as_view({
            'get': 'list',
            'post': 'create',
        }),
        name='event'
    ),

    url(
        r'^api/v1/event/(?P<pk>\d+)/$', 
        views.EventView.as_view({
            'get': 'retrieve',
            'put': 'update',
            'patch': 'update',
        }),
        name='event-detail'
    ),    

    url(
        r'^api/v1/group/$', 
        views.GroupView.as_view({
            'get': 'list',
            'post': 'create',
        }),
        name='group'
    ),

    url(
        r'^api/v1/group/(?P<pk>\d+)/$', 
        views.GroupView.as_view({
            'get': 'retrieve',
            'put': 'update',
            'patch': 'update',
        }),
        name='group-detail'
    ),    

    url(
        r'^api/v1/member_group/$', 
        views.MemberGroupView.as_view({
            'get': 'list',
            'post': 'create',
        }),
        name='member-group'
    ),

    url(
        r'^api/v1/member_group/(?P<pk>\d+)/$', 
        views.MemberGroupView.as_view({
            'get': 'retrieve',
            'put': 'update',
            'patch': 'update',
        }),
        name='member-group-detail'
    ),    

    url(
        r'^api/v1/attendance/$', 
        views.AttendanceView.as_view({
            'get': 'list',
            'post': 'create',
        }),
        name='attendance'
    ),

    url(
        r'^api/v1/attendance/(?P<pk>\d+)/$', 
        views.AttendanceView.as_view({
            'get': 'retrieve',
            'put': 'update',
            'patch': 'update',
        }),
        name='attendance-detail'
    ),    
]

authentication/models.py
from django.db import models

# Create your models here.

authentication/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordResetForm
from django.core.urlresolvers import reverse
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_control, never_cache
from django.views.generic.edit import FormView


class LoginRequiredMixIn(object):
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(LoginRequiredMixIn, self).dispatch(request, *args, **kwargs)


class NoCacheMixIn(object):
    @method_decorator(cache_control(no_cache=True))
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        return super(NoCacheMixIn, self).dispatch(request, *args, **kwargs)


class PasswordResetView(NoCacheMixIn, FormView):
    template_name = 'authentication/password_reset.html'
    form_class = PasswordResetForm

    def get_success_url(self):
        return reverse('authentication:password_reset_done')

authentication/templates/authentication/base.html
{% extends "base.html" %}

{% load i18n %}
{% load staticfiles %}

{% block title %}{% trans 'Church Life' %}{% endblock %}

{% block extrastyle %}
    <link rel="stylesheet" type="text/css" href='{% static "authentication/css/login.css" %}' />
{% endblock %}

{% block content %}

    <div class="row login-container">
        <div class="{% block login_container_classes %}{% endblock %} login-container-column">
            <div class="login-container-top">
                <div class="login-logo">
                    <div id="login-logo"></div>
                </div>
            </div>

            <div class="login-separator"></div>

            <div class="login-container-bottom">
                <h1 class="login-title">{% block login_title %}{% endblock %}</h1>

                {% block login_content %}{% endblock %}

            </div>
            {% include "footer.html" %}
        </div>
    </div>

{% endblock %}

authentication/templates/authentication/login.html
{% extends "authentication/base.html" %}

{% load bootstrap %}
{% load i18n %}

{% block login_title %}{% trans 'Sign into Church Life' %}{% endblock %}

{% block login_container_classes %}col-xs-offset-3 col-xs-6{% endblock %}

{% block login_content %}

    <form method="post" action="?next={{ request.GET.next }}" id="login">
        {% csrf_token %}

        <div class="row">
            <div class="col-xs-12">
                <label class="control-label" for="{{ form.username.auto_id }}">{% trans 'Email Address:' %}</label>
                <div class="form-group{% if form.username.errors %} has-error{% endif %}">
                    <input id="id_username" type="text" name="username" class="form-control" />
                    <span class="input-icon fui-user"></span>
                </div>
                {% for error in form.username.errors %}
                    <div class="login-input-error">{{error}}</div>
                {% endfor %}
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12">
                <label class="control-label" for="{{ form.password.auto_id }}">{% trans 'Password:' %}</label>
                <div class="form-group{% if form.password.errors %} has-error{% endif %}">
                    <input id="id_password" type="password" name="password" class="form-control" />
                    <span class="input-icon fui-lock"></span>
                </div>
                {% for error in form.password.errors %}
                    <div class="login-input-error">{{error}}</div>
                {% endfor %}
            </div>
        </div>

        <div class="login-controls clearfix">
            <div class="login-control-submit">
                <input type="submit" value="{% trans 'Sign In' %}" class="pull-left" />
            </div>
            <div class="login-control-help">
                <a href="{% url 'authentication:password_reset' %}" class="pull-right login-help">{% trans "Help! I'm having trouble logging in." %}</a>
            </div>
        </div>

        <div class="clearfix"></div>

        {% if form.errors %}
            <div class="login-input-error">
                {% trans "We didn't recognize the email address or password you entered. Please try again." %}
            </div>
        {% endif %}

    </form>

{% endblock %}

authentication/templates/authentication/password_reset.html
{% extends "authentication/base.html" %}

{% load bootstrap %}
{% load i18n %}

{% block login_title %}{% trans 'Need Help Logging In?' %}{% endblock %}

{% block login_container_classes %}col-xs-offset-3 col-xs-6{% endblock %}

{% block login_content %}

    <div>
        {% trans 'Enter the email address* associated with your account and we will send you a link to reset your password.' %}
    </div>

    <br />

    <form action="." id="login" method="post">
        {% csrf_token %}

        <div class="row">
            <div class="col-xs-12">
                <label class="control-label" for="{{ form.email.auto_id }}">{% trans 'Email Address:' %}</label>
                <div class="form-group{% if form.email.errors %} has-error{% endif %}">
                    <input id="id_email" type="text" name="email" class="form-control" />
                </div>
                {% for error in form.email.errors %}
                    <div class="login-input-error">{{error}}</div>
                {% endfor %}
            </div>
        </div>

        <div class="login-notice">{% trans '*If any issue, please contact the System Administrator.' %}</div>

        <div class="login-bottom-button">
            <input class="btn-stretch" type="submit" Value="{% trans 'Request Password Reset' %}" />
        </div>

    </form>

{% endblock %}

authentication/templates/authentication/password_reset_done.html
{% extends "authentication/base.html" %}

{% load bootstrap %}
{% load i18n %}

{% block login_title %}{% trans 'Need Help Logging In?' %}{% endblock %}

{% block login_container_classes %}col-xs-offset-3 col-xs-6{% endblock %}

{% block login_content %}

    <div class="login-text">

        {% blocktrans with email=email %}An email has been sent to <a href="mailto:{{ email }}">{{ email }}</a> to start the Password Reset Process.
        Please follow the instructions within the email to continue.{% endblocktrans %}

        <br />
        <br />

        {% trans "PS. Don't forget to check your spam folder as system messages may automatically be routed there by your email provider." %}

        <br />
        <br />

    </div>
{% endblock %}