authentication/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns('',
    # The password reset form view:
    url(r'^password_reset/$',
        views.PasswordResetView.as_view(),
        name='password_reset'
    ),
    # The password reset confirmation view:
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'django.contrib.auth.views.password_reset_confirm',
        name='password_reset_confirm'
    ),

    url(r'^login/$',
        'django.contrib.auth.views.login',
        kwargs={'template_name': 'authentication/login.html'},
        name='login'
    ),

    url(r'^logout/$',
        'django.contrib.auth.views.logout',
        kwargs={'next_page': '/login'},
        name='logout'),

    url(
        r'^password/reset/done/$',
        'django.contrib.auth.views.password_reset_done',
        kwargs={'template_name': 'authentication/password_reset_done.html'},
        name='password_reset_done'
    ),
)

core/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import (login,
                                       logout)
from . import views

urlpatterns = [
    url(r'^', include('churchlife.authentication.urls', namespace='authentication')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.IndexView.as_view(), name='index'),

    url(
        r'^api/v1/user_session/$', 
        views.UserSessionView.as_view({
            'get': 'list',
            # 'post': 'create',
        }),
        name='user_session'
    ),

    url(
        r'^api/v1/user/$', 
        views.UserView.as_view({
            'get': 'list',
            # 'post': 'create',
        }),
        name='user'
    ),

    url(
        r'^api/v1/member/$', 
        views.MemberView.as_view({
            'get': 'list',
            'post': 'create',
        }),
        name='member'
    ),

    url(
        r'^api/v1/member/(?P<pk>\d+)/$', 
        views.MemberView.as_view({
            'get': 'retrieve',
            'put': 'update',
            'patch': 'update',
        }),
        name='member-detail'
    ), 

    url(
        r'^api/v1/member/search/$', 
        views.MemberSearchView.as_view({
            'get': 'list'
        }),
        name='member-search'
    ),

    url(
        r'^api/v1/organization/$', 
        views.OrganizationView.as_view({
            'get': 'list',
            'post': 'create',
        }),
        name='organization'
    ),

    url(
        r'^api/v1/organization/(?P<pk>\d+)/$', 
        views.OrganizationView.as_view({
            'get': 'retrieve',
            'put': 'update',
            'patch': 'update',
        }),
        name='organization-detail'
    ),    

    url(
        r'^api/v1/event/$', 
        views.EventView.as_view({
            'get': 'list',
            'post': 'create',
        }),
        name='event'
    ),

    url(
        r'^api/v1/event/(?P<pk>\d+)/$', 
        views.EventView.as_view({
            'get': 'retrieve',
            'put': 'update',
            'patch': 'update',
        }),
        name='event-detail'
    ),    

    url(
        r'^api/v1/group/$', 
        views.GroupView.as_view({
            'get': 'list',
            'post': 'create',
        }),
        name='group'
    ),

    url(
        r'^api/v1/group/(?P<pk>\d+)/$', 
        views.GroupView.as_view({
            'get': 'retrieve',
            'put': 'update',
            'patch': 'update',
        }),
        name='group-detail'
    ),    

    url(
        r'^api/v1/member_group/$', 
        views.MemberGroupView.as_view({
            'get': 'list',
            'post': 'create',
        }),
        name='member-group'
    ),

    url(
        r'^api/v1/member_group/(?P<pk>\d+)/$', 
        views.MemberGroupView.as_view({
            'get': 'retrieve',
            'put': 'update',
            'patch': 'update',
        }),
        name='member-group-detail'
    ),    

    url(
        r'^api/v1/attendance/$', 
        views.AttendanceView.as_view({
            'get': 'list',
            'post': 'create',
        }),
        name='attendance'
    ),

    url(
        r'^api/v1/attendance/(?P<pk>\d+)/$', 
        views.AttendanceView.as_view({
            'get': 'retrieve',
            'put': 'update',
            'patch': 'update',
        }),
        name='attendance-detail'
    ),    
]

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
<!--[if IE 7]><html class="ie ie7" lang="en"><![endif]-->
<!--[if IE 8]><html class="ie ie8" lang="en"><![endif]-->
{% load i18n %}
{% load bootstrap %}

<html lang="en">
    <head>
        <meta charset="utf-8" />

        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="" />
        <meta name="author" content="" />

        {# Disable the iPad/iPhone automatic phone conversion into a link: #}
        <meta name="format-detection" content="telephone=no">

        <title>{% block title %}{% endblock %}</title>

        <!-- Bootstrap + FlatUI (base CSS for an application). -->
        <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/libs/bootstrap/bootstrap.min.css" />
        <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/libs/flat-ui/flat-ui.css" />
        <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/libs/flat-ui/datepicker.css" />
        <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/libs/backbone/backbone.modal.css" />
        <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/libs/backbone/backbone.modal.theme.css" />

        <!-- Base CSS styles (styles applied to generic HTML elements). -->
        <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/base.css" />

        <!-- Main layout and shared CSS styles. -->
        <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/main.css" />

        <!-- CSS override for our libraries (Bootstrap, FlatUI, etc.) -->
        <!-- <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/override/bootstrap.css" /> -->
        <!-- <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/override/bootstrap-tagsinput.css" /> -->
        <!-- <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/override/flat-ui/typeahead.css" /> -->

        <!-- CSS styles for each application/module. -->
        {% block extrastyle %}{% endblock %}

        <!--[if lte IE 10]>
          <link rel="stylesheet" type="text/css" href="/static/css/ie/ie.css?cb=20131214" />
        <![endif]-->

        <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
        <!--[if lt IE 9]>
          <script type="text/javascript" src="/static/js/libs/flat-ui/html5shiv.js?cb=20131214"></script>
          <script type="text/javascript" src="/static/js/libs/flat-ui/respond.min.js?cb=20131214"></script>
        <![endif]-->
    </head>

    <body>
        {% block drawer %}{% endblock %}

        <div class="main-body-container">
            <!-- BEGIN Header -->
                {% block header %}{% endblock %}
            <!-- END Header -->

            <div class="container">
                <!-- BEGIN Main Content -->
                    {% block content %}{% endblock %}
                <!-- END Main Content -->
            </div>
        </div>

        {% block modal %}{% endblock %}

        {% block extrajs %}{% endblock %}
    </body>
</html>

templates/base_authenticated.html
{% extends "base.html" %}

{% load i18n %}

{% block header %}

    <header class="clearfix">
        <div class="container header-container">
            <div class="header-left">
                <div class="pull-left">
                    <div class="main-logo"></div>
                </div>
            </div>

            <div class="header-right">
                <div class="btn-group">
                    <div class="header-right-text">{% blocktrans with first_name=request.user.first_name last_name=request.user.last_name %}Welcome, <strong>{{first_name}} {{last_name}}</strong>{% endblocktrans %}</div>
                    <button class="btn btn-default dropdown-toggle btn-xs" type="button" data-toggle="dropdown">
                        <span class="caret"></span>
                    </button>
                    <span class="dropdown-arrow"></span>
                    <ul class="dropdown-menu pull-right">
                        {% if user.is_active %}
                        <li><a href="">{% trans 'My Profile' %}</a></li>
                        {% endif %}
                        <li><a href="{% url 'authentication:logout' %}">{% trans 'Sign Out' %}</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </header>

{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-xs-12 main-container">
            <div class="main-container-content" id="main-container-content">
            </div>
            {% include "footer.html" %}
        </div>
    </div>

{% endblock %}

templates/footer.html
<footer class="clearfix">
    <div class="row">
        <div class="col-xs-12 col-sm-8">
            Copyright @ Mainland Scholars' Work, Anaheim, California
        </div>
    </div>
</footer>

templates/jquery.html
{% comment %}
    FlatUI requires jquery 2.x, but it will run with an old 1.x too (although in a flaky way), so 2.x is always preferred.
    2.x doesn't support IE below version 9, thus with this conditional we tell to use an old 1.8.x jquery on those browsers.
{% endcomment %}
<!--[if lt IE 9]>
  <script type="text/javascript" src="/static/js/libs/flat-ui/jquery-1.8.3.min.js?cb=20131214"></script>
<![endif]-->

{% comment %}
   For other browsers (Firefox, Chrome, etc) always use the new 2.x jquery.
   (this holds true for IE 10 and above too, which doesn't support IE conditionals).
{% endcomment %}
<!--[if !IE]> -->
  <script type="text/javascript" src="/static/js/libs/flat-ui/jquery-2.0.3.min.js?cb=20131214"></script>
<!-- <![endif]-->

{% comment %}
    IE 9 supports 2.x, and IE conditionals, so for that browser also use 2.x.
{% endcomment %}
<!--[if IE 9]>
  <script type="text/javascript" src="/static/js/libs/flat-ui/jquery-2.0.3.min.js?cb=20131214"></script>
<![endif]-->

{% comment %}
    For IE below 9 use the jquery placeholder library.
{% endcomment %}
<!--[if lte IE 9]>
  <script type="text/javascript" src="/static/js/libs/flat-ui/jquery.placeholder.js?cb=20131214"></script>
  <script type="text/javascript" src="/static/js/tlx/ie/ie.js?cb=20131214"></script>
<![endif]-->